import { Museum } from '../../museums/schemas/museum.schema';

export const museumsSeed: Partial<Museum>[] = [
  {
    name: '北京故宫博物院',
    description: '中国最大的古代文化艺术博物馆，收藏有180多万件珍贵文物，是世界现存最大的古代宫殿建筑群。',
    address: '北京市东城区景山前街4号',
    city: '北京',
    province: '北京市',
    images: ['https://picsum.photos/800/600?random=1'],
    coverImage: 'https://picsum.photos/800/600?random=1',
    phone: '010-85007938',
    website: 'https://www.dpm.org.cn',
    openingHours: '8:30-17:00（4月1日-10月31日）；8:30-16:30（11月1日-3月31日）周一闭馆',
    ticketInfo: '旺季60元，淡季40元',
    tags: ['历史', '文化', '宫殿', '皇家'],
    category: '历史博物馆',
    latitude: 39.9163,
    longitude: 116.3972,
    rating: { average: 4.9, count: 125680 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: true,
    introduction: '故宫又称紫禁城，是明清两代的皇家宫殿，占地72万平方米，建筑面积约15万平方米，有大小宫殿七十多座，房屋九千余间。',
    trafficInfo: '地铁1号线天安门东站或天安门西站下车，步行可达。',
    notice: '需提前在官网预约购票，周一闭馆（法定节假日除外）',
  },
  {
    name: '中国国家博物馆',
    description: '世界上单体建筑面积最大的博物馆之一，收藏中华文明5000年历史文物，是中华文化的祠堂和祖庙。',
    address: '北京市东城区东长安街16号',
    city: '北京',
    province: '北京市',
    images: ['https://picsum.photos/800/600?random=2'],
    coverImage: 'https://picsum.photos/800/600?random=2',
    phone: '010-65116400',
    website: 'http://www.chnmuseum.cn',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '文化', '国家宝藏'],
    category: '综合博物馆',
    latitude: 39.9042,
    longitude: 116.4074,
    rating: { average: 4.8, count: 98520 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: true,
    introduction: '中国国家博物馆是代表国家收藏、研究、展示、阐释中华文化代表性物证的最高历史文化艺术殿堂。',
    trafficInfo: '地铁1号线天安门东站下车，步行可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '上海博物馆',
    description: '以古代艺术为主的综合性博物馆，馆藏珍贵文物近百万件，尤以青铜器、陶瓷器、书法、绘画为特色。',
    address: '上海市黄浦区人民大道201号',
    city: '上海',
    province: '上海市',
    images: ['https://picsum.photos/800/600?random=3'],
    coverImage: 'https://picsum.photos/800/600?random=3',
    phone: '021-63723500',
    website: 'https://www.shanghaimuseum.net',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['艺术', '青铜器', '陶瓷', '书画'],
    category: '艺术博物馆',
    latitude: 31.2304,
    longitude: 121.4737,
    rating: { average: 4.7, count: 87650 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: true,
    introduction: '上海博物馆创建于1952年，是一座大型的中国古代艺术博物馆，馆藏珍贵文物近百万件。',
    trafficInfo: '地铁1、2、8号线人民广场站下车，步行可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '南京博物院',
    description: '中国三大博物馆之一，馆藏文物43万余件，其中国宝级文物和国家一级文物数量位居全国前列。',
    address: '江苏省南京市玄武区中山东路321号',
    city: '南京',
    province: '江苏省',
    images: ['https://picsum.photos/800/600?random=4'],
    coverImage: 'https://picsum.photos/800/600?random=4',
    phone: '025-84807923',
    website: 'http://www.njmuseum.com',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '文物', '六朝古都'],
    category: '综合博物馆',
    latitude: 32.0408,
    longitude: 118.7969,
    rating: { average: 4.8, count: 76890 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: true,
    introduction: '南京博物院是中国创建最早的博物馆，中国第一座由国家投资兴建的大型综合类博物馆。',
    trafficInfo: '地铁2号线明故宫站下车，步行可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '陕西历史博物馆',
    description: '中国第一座大型现代化国家级博物馆，被誉为"古都明珠，华夏宝库"，馆藏文物171万余件。',
    address: '陕西省西安市雁塔区小寨东路91号',
    city: '西安',
    province: '陕西省',
    images: ['https://picsum.photos/800/600?random=5'],
    coverImage: 'https://picsum.photos/800/600?random=5',
    phone: '029-85253806',
    website: 'http://www.sxhm.com',
    openingHours: '9:00-17:30（周一闭馆）',
    ticketInfo: '免费（需预约），珍宝馆30元',
    tags: ['历史', '文物', '唐朝', '丝路'],
    category: '历史博物馆',
    latitude: 34.2287,
    longitude: 108.9493,
    rating: { average: 4.8, count: 89340 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: true,
    introduction: '陕西历史博物馆是首批中国"AAAA"级旅游景点，馆藏文物上起远古人类初始阶段，下至近代社会.',
    trafficInfo: '地铁2、3号线小寨站下车，步行可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '湖南省博物馆',
    description: '湖南省最大的历史艺术博物馆，以马王堆汉墓出土文物最具特色，藏品达18万余件。',
    address: '湖南省长沙市开福区东风路50号',
    city: '长沙',
    province: '湖南省',
    images: ['https://picsum.photos/800/600?random=6'],
    coverImage: 'https://picsum.photos/800/600?random=6',
    phone: '0731-84415833',
    website: 'http://www.hnmuseum.com',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '马王堆', '汉代', '辛追'],
    category: '综合博物馆',
    latitude: 28.2067,
    longitude: 112.9843,
    rating: { average: 4.7, count: 65230 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: true,
    introduction: '湖南省博物馆是湖南省最大的历史艺术博物馆，以马王堆汉墓出土文物、商周青铜器等最具特色。',
    trafficInfo: '地铁3号线烈士公园东站下车，步行可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '河南博物院',
    description: '中国建立较早的博物馆之一，馆藏文物17万余件，尤以史前文物、商周青铜器、历代陶瓷器最具特色。',
    address: '河南省郑州市金水区农业路8号',
    city: '郑州',
    province: '河南省',
    images: ['https://picsum.photos/800/600?random=7'],
    coverImage: 'https://picsum.photos/800/600?random=7',
    phone: '0371-63511237',
    website: 'https://www.chnmus.net',
    openingHours: '9:00-17:30（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '青铜器', '中原', '古都'],
    category: '历史博物馆',
    latitude: 34.7663,
    longitude: 113.6534,
    rating: { average: 4.6, count: 54120 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: false,
    introduction: '河南博物院创建于1927年，是中国建立较早的博物馆之一，馆藏精品包括贾湖骨笛、妇好鸮尊等。',
    trafficInfo: '公交B1、B2、B11路博物院站下车。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '浙江省博物馆',
    description: '浙江省内最大的综合性人文科学博物馆，馆藏文物十万余件，是展示浙江悠久历史和灿烂文化的重要窗口。',
    address: '浙江省杭州市西湖区孤山路25号',
    city: '杭州',
    province: '浙江省',
    images: ['https://picsum.photos/800/600?random=8'],
    coverImage: 'https://picsum.photos/800/600?random=8',
    phone: '0571-87971177',
    website: 'http://www.zhejiangmuseum.com',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '文化', '江南', '越国'],
    category: '综合博物馆',
    latitude: 30.2509,
    longitude: 120.1403,
    rating: { average: 4.6, count: 48960 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: false,
    introduction: '浙江省博物馆始建于1929年，是浙江省内最大的集收藏、陈列、研究于一体的综合性人文科学博物馆。',
    trafficInfo: '公交Y9路、Y10路浙江博物馆站下车。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '广东省博物馆',
    description: '华南地区最大的综合性博物馆，馆藏18万余件，以岭南文化、海上丝绸之路文物为特色。',
    address: '广东省广州市天河区珠江东路2号',
    city: '广州',
    province: '广东省',
    images: ['https://picsum.photos/800/600?random=9'],
    coverImage: 'https://picsum.photos/800/600?random=9',
    phone: '020-38046886',
    website: 'http://www.gdmuseum.com',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '岭南文化', '海上丝绸之路'],
    category: '综合博物馆',
    latitude: 23.1151,
    longitude: 113.3245,
    rating: { average: 4.6, count: 52340 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: false,
    introduction: '广东省博物馆是华南地区最大的综合性博物馆，展示岭南文化精粹和海上丝绸之路历史。',
    trafficInfo: '地铁3号线珠江新城站或5号线猎德站下车，步行可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '四川省博物院',
    description: '西南地区最大的综合性博物馆，馆藏文物26万余件，以巴蜀文化、少数民族文物为特色。',
    address: '四川省成都市青羊区浣花南路251号',
    city: '成都',
    province: '四川省',
    images: ['https://picsum.photos/800/600?random=10'],
    coverImage: 'https://picsum.photos/800/600?random=10',
    phone: '028-65521888',
    website: 'http://www.scmuseum.cn',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '巴蜀文化', '三星堆', '熊猫'],
    category: '综合博物馆',
    latitude: 30.6578,
    longitude: 104.0434,
    rating: { average: 4.5, count: 45230 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: false,
    introduction: '四川博物院是西南地区最大的综合性博物馆，展示巴蜀文化、四川历史和少数民族风情。',
    trafficInfo: '公交19、35、58路送仙桥站下车。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '苏州博物馆',
    description: '由著名建筑师贝聿铭设计，馆藏文物3万余件，以出土文物、明清书画和工艺品见长。',
    address: '江苏省苏州市姑苏区东北街204号',
    city: '苏州',
    province: '江苏省',
    images: ['https://picsum.photos/800/600?random=11'],
    coverImage: 'https://picsum.photos/800/600?random=11',
    phone: '0512-67575666',
    website: 'http://www.szmuseum.com',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['艺术', '建筑', '江南', '园林'],
    category: '艺术博物馆',
    latitude: 31.3153,
    longitude: 120.6248,
    rating: { average: 4.8, count: 67890 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: true,
    introduction: '苏州博物馆由著名建筑师贝聿铭设计，建筑本身就是一件艺术品，馆藏以明清书画和江南工艺品为主。',
    trafficInfo: '地铁4号线北寺塔站下车，步行可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '天津博物馆',
    description: '中国较早建立的博物馆之一，馆藏文物近20万件，以甲骨、青铜器、玉器、书画为特色。',
    address: '天津市河西区平江道62号',
    city: '天津',
    province: '天津市',
    images: ['https://picsum.photos/800/600?random=12'],
    coverImage: 'https://picsum.photos/800/600?random=12',
    phone: '022-83883000',
    website: 'https://www.tjbwg.com',
    openingHours: '9:00-16:30（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '文物', '书画', '玉器'],
    category: '综合博物馆',
    latitude: 39.0842,
    longitude: 117.2009,
    rating: { average: 4.5, count: 38450 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: false,
    introduction: '天津博物馆是一座大型历史艺术类综合性博物馆，馆藏精品包括甲骨文、青铜器、历代书画等。',
    trafficInfo: '地铁5、6号线文化中心站下车，步行可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '辽宁省博物馆',
    description: '新中国建立的第一座博物馆，馆藏文物近12万件，以晋唐宋元书画珍品著称。',
    address: '辽宁省沈阳市浑南区智慧三街157号',
    city: '沈阳',
    province: '辽宁省',
    images: ['https://picsum.photos/800/600?random=13'],
    coverImage: 'https://picsum.photos/800/600?random=13',
    phone: '024-22741193',
    website: 'http://www.lnmuseum.com',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '书画', '东北', '清前史'],
    category: '综合博物馆',
    latitude: 41.6651,
    longitude: 123.3912,
    rating: { average: 4.6, count: 32150 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: false,
    introduction: '辽宁省博物馆是新中国建立的第一座博物馆，以晋唐宋元书画、清代瓷器等珍贵藏品闻名。',
    trafficInfo: '地铁2号线世纪大厦站下车，换乘公交可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
  {
    name: '重庆中国三峡博物馆',
    description: '以巴渝文化、三峡文化为特色的综合性博物馆，馆藏文物10万余件，是重庆的城市名片。',
    address: '重庆市渝中区人民路236号',
    city: '重庆',
    province: '重庆市',
    images: ['https://picsum.photos/800/600?random=14'],
    coverImage: 'https://picsum.photos/800/600?random=14',
    phone: '023-63679000',
    website: 'http://www.3gmuseum.cn',
    openingHours: '9:00-17:00（周一闭馆）',
    ticketInfo: '免费（需预约）',
    tags: ['历史', '三峡', '巴渝文化', '抗战'],
    category: '综合博物馆',
    latitude: 29.5585,
    longitude: 106.5492,
    rating: { average: 4.6, count: 43280 },
    facilities: ['讲解服务', '行李寄存', '餐饮服务', '文创商店'],
    isActive: true,
    isFeatured: false,
    introduction: '重庆中国三峡博物馆是保护、研究、展示重庆和三峡地区历史文化遗产的综合性博物馆。',
    trafficInfo: '轻轨2号线曾家岩站下车，步行可达。',
    notice: '需提前在官网预约，周一闭馆',
  },
];